// Lower Dorn's Deep, palace, second floor
IF
Global("O#NPCwithoutT1","GLOBAL",0)
InParty("O#Holvir")
InParty("O#Korin")
InParty("O#Nella")
InParty("O#Severn")
THEN
RESPONSE #100
SetGlobal("O#NPCwithoutT1","GLOBAL",1)
Continue()
END

IF
Global("O#NPCSevernTeri14","GLOBAL",0)
InParty("O#Severn")
InParty("O#Teri")
PartyHasItem("MARKETH")
THEN
RESPONSE #100
SetGlobal("O#NPCSevernTeri14","GLOBAL",1)
Continue()
END