// Sea of Moving Ice, caves level 2
IF
Global("O#NPCKorinSevern11","GLOBAL",0)
InParty("O#Korin")
InParty("O#Severn")
InParty("O#Teri")
THEN
RESPONSE #100
SetGlobal("O#NPCKorinSevern11","GLOBAL",1)
Continue()
END

IF
Global("O#NPCNellaTeri11","GLOBAL",0)
InParty("O#Nella")
InParty("O#Teri")
GlobalGT("O#XactileTalked","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("O#NPCNellaTeri11","GLOBAL",1)
Continue()
END